import Foundation

private let CDN = "https://cdn.shopify.com/s/files/1/0809/3358/5151/files/"

enum ShopifyRepo {

    static let categories: [Category] = [
        Category(id: "all",          name: "All"),
        Category(id: "tracksuits",   name: "Tracksuits"),
        Category(id: "denim",        name: "Denim"),
        Category(id: "tops",         name: "Tops"),
        Category(id: "accessories",  name: "Accessories"),
        Category(id: "eves-wardrobe",name: "Eve's Wardrobe"),
    ]

    static let popupEvents: [PopupEvent] = [
        PopupEvent(date: "June 21",   note: "Location announced 48h prior"),
        PopupEvent(date: "July 21",   note: "Location announced 48h prior"),
        PopupEvent(date: "August 20", note: "Location announced 48h prior"),
    ]

    static let products: [Product] = [
        // TRACKSUITS
        Product(id:"ojos-jacket",handle:"ojos-velour-track-jacket",title:"OJOS Velour Track Jacket",price:109.99,
            description:"A premium velour track jacket featuring a burgundy, black, red, and mauve colorblock design. The piece includes a back graphic reading \"The Eyes Chico They Never Lie\" and branded sleeve embroidery.",
            imageUrl:CDN+"77963_672f7575-e89e-4633-84c4-1a9113e32c24.jpg",category:"tracksuits",
            sizes:["XS","S","M","L","XL"],colors:["Ojos"],isFeatured:true,tags:["Bestseller"]),
        Product(id:"ojos-pant",handle:"ojos-velour-track-pants",title:"OJOS Velour Track Pants",price:69.99,
            description:"Matching track pant to the OJOS Velour Track Jacket. Colorblock velour with elastic waist, tapered leg, and branded details.",
            imageUrl:CDN+"rn-image_picker_lib_temp_b20f8220-a544-4191-9306-ecda6711ceea.png",category:"tracksuits",
            sizes:["One Size"],colors:["Rose Gold"],tags:["Pair with jacket"]),
        Product(id:"ovum-jacket",handle:"ovum-satin-track-jacket-pearl",title:"OVUM Satin Track Jacket — Pearl",price:159.99,
            description:"A premium track jacket featuring clean retro-sport structure and controlled color blocking. The upper half of the Melato uniform.",
            imageUrl:CDN+"melato-ovum-satin-track-jacket-pearl.jpg",category:"tracksuits",
            sizes:["XS","S","M","L","XL"],colors:["Pearl"],isFeatured:true,isNew:true,tags:["New Drop","OVUM"]),
        Product(id:"ovum-pant",handle:"ovum-satin-track-pant-pearl",title:"OVUM Satin Track Pant — Pearl",price:149.99,
            description:"The matching satin track pant to the OVUM Jacket. Pearl finish, elastic waistband with adjustable drawstring, tapered leg.",
            imageUrl:CDN+"melato-ovum-satin-track-pant-pearl.jpg",category:"tracksuits",
            sizes:["XS","S","M","L","XL"],colors:["Pearl"],isNew:true,tags:["New Drop","OVUM"]),
        Product(id:"divididos-jacket",handle:"divididos-velour-track-jacket",title:"Divididos Velour Track Jacket",price:89.99,
            description:"Heritage-inspired velour construction with a distinctive divided colorblock layout. Full front zip, structured collar, branded embroidery.",
            imageUrl:CDN+"rn-image_picker_lib_temp_c6111df6-11a0-4d6f-af91-e1f5119e7cc7.jpg",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Divididos"],isFeatured:true,tags:["Core"]),
        Product(id:"divididos-pant",handle:"divididos-velour-track-pant",title:"Divididos Velour Track Pant",price:59.99,
            description:"Matching track pant to the Divididos Velour Track Jacket. Heritage colorblock design, elastic waist, side pockets.",
            imageUrl:CDN+"melato-divididos-velour-track-pant-front.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Divididos"]),
        Product(id:"conquista-jacket",handle:"conquista-velour-track-jacket",title:"Conquista Velour Track Jacket",price:89.99,
            description:"Mission-coded color-blocking with controlled presence. Teal, purple, lime, orange, burgundy, and black colorblock layout with graphic back detailing.",
            imageUrl:CDN+"melato-conquista-velour-track-jacket-alternate.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Conquista"],isFeatured:true,tags:["Bold"]),
        Product(id:"conquista-pant",handle:"conquista-velour-track-pant",title:"Conquista Velour Track Pant",price:59.99,
            description:"Matching pant to the Conquista Track Jacket. Bold colorblock construction, elastic waist with drawstring, tapered leg.",
            imageUrl:CDN+"melato-conquista-velour-track-pant-front.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Conquista"]),
        Product(id:"chu-jacket",handle:"chu-velour-track-jacket",title:"Chū Velour Track Jacket",price:89.99,
            description:"Grey blue geometric colorblock velour jacket with structured silhouette. A quieter expression of the Melato tracksuit identity.",
            imageUrl:CDN+"melato-chu-velour-track-jacket-alternate.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Chū"]),
        Product(id:"chu-pant",handle:"chu-velour-track-pant",title:"Chū Velour Track Pant",price:59.99,
            description:"Matching track pant to the Chū Velour Jacket. Grey blue geometric colorblock, elastic waist, tapered cut.",
            imageUrl:CDN+"melato-chu-velour-track-pant-front.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Chū"]),
        Product(id:"passion-jacket",handle:"passion-fruit-velour-track-jacket",title:"Passion Fruit Velour Track Jacket",price:89.99,
            description:"Earth tone, warm colorblock velour jacket. One of the more expressive pieces in the tracksuit lineup.",
            imageUrl:CDN+"rn-image_picker_lib_temp_f475785a-aff5-4826-8c6c-2a16cf37d44b.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Passion Fruit"]),
        Product(id:"passion-pant",handle:"passion-fruit-velour-track-pant",title:"Passion Fruit Velour Track Pant",price:59.99,
            description:"Matching pant to the Passion Fruit Velour Track Jacket. Earth tone colorblock, relaxed athletic fit.",
            imageUrl:CDN+"rn-image_picker_lib_temp_ce964744-d66c-4a02-977d-a405915e7bc8.jpg",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Passion Fruit"]),
        Product(id:"midas-jacket",handle:"midas-runner-track-jacket",title:"Midas Runner Track Jacket",price:149.99,
            description:"The runner silhouette — lighter construction, longer hang, athletic performance shape. Sits above the core velour line in feel and finish.",
            imageUrl:CDN+"rn-image_picker_lib_temp_7986447b-7784-4dec-9b07-842914a3a3df.png",category:"tracksuits",
            sizes:["XS","S","M","L","XL"],colors:["Midas"],isFeatured:true,tags:["Premium"]),
        Product(id:"midas-pant",handle:"midas-runner-track-pants",title:"Midas Runner Track Pants",price:89.99,
            description:"Matching runner track pant to the Midas jacket. Lightweight athletic construction, tapered leg, elastic waist with cord.",
            imageUrl:CDN+"rn-image_picker_lib_temp_7834f71d-51bd-4a28-b1d8-cd33929d1fce.png",category:"tracksuits",
            sizes:["XS","S","M","L","XL"],colors:["Midas"]),
        Product(id:"reliance-jacket",handle:"reliance-bamboo-track-jacket",title:"Reliance Bamboo Track Jacket",price:99.99,
            description:"Bamboo-blend track jacket in black salmon colorblock. Softer hand than velour — worn close or relaxed.",
            imageUrl:CDN+"rn-image_picker_lib_temp_1964916b-e416-48f1-a69d-9cb84f34f43e.png",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Black Salmon"]),
        Product(id:"reliance-pant",handle:"reliance-bamboo-track-pant",title:"Reliance Bamboo Track Pant",price:59.99,
            description:"Bamboo-blend matching track pant. Black salmon colorblock, elastic waist, tapered leg.",
            imageUrl:CDN+"rn-image_picker_lib_temp_0c141d33-bb82-423a-8fbb-c78fd499336d.jpg",category:"tracksuits",
            sizes:["S","M","L","XL"],colors:["Black Salmon"]),

        // DENIM
        Product(id:"9-to-noir",handle:"9-to-noir-tailored-flare-pant",title:"9 to Noir Tailored Flare Pant",price:74.99,
            description:"A tailored flare silhouette in deep noir. Cut with precision — from the office to the after.",
            imageUrl:CDN+"rn-image_picker_lib_temp_2f725dc5-48e3-4781-bcaa-1763225b353e.jpg",category:"denim",
            sizes:["S","M","L"],colors:["Noir"]),
        Product(id:"hendrix-jean",handle:"hendrix-distressed-flare-jean",title:"Hendrix Distressed Flare Jean",price:79.99,
            description:"Distressed flare denim with a vintage athletic soul. Sits at the intersection of seventies denim culture and modern street.",
            imageUrl:CDN+"rn-image_picker_lib_temp_593dec29-b17f-4f96-abfd-acbf64de4190.png",category:"denim",
            sizes:["28","30","32","34","36"],colors:["Hendrix"],isFeatured:true),
        Product(id:"berry-jean",handle:"berry-distressed-slim-jean",title:"Berry Distressed Slim Jean",price:139.99,
            description:"Slim cut distressed denim in a rich berry wash. The distressing is intentional, not decorative.",
            imageUrl:CDN+"rn-image_picker_lib_temp_c33e3385-56f5-4150-b1dd-57c90db51f1b.png",category:"denim",
            sizes:["28","30","32","34","36"],colors:["Berry"]),
        Product(id:"dirt-rich",handle:"dirt-rich-denim-flare-jean",title:"Dirt Rich Denim Flare Jean",price:89.99,
            description:"Raw-edge flare denim with earth-toned washes and heavy character. Built for those who wear their clothes, not just own them.",
            imageUrl:CDN+"rn-image_picker_lib_temp_f57c49d5-d437-4762-9e2a-f6a0dfb03533.jpg",category:"denim",
            sizes:["24","26","28","30","32"],colors:["Dirt Rich"]),
        Product(id:"nuit-blanche",handle:"nuit-blanche-zip-flare-jean",title:"Nuit Blanche Zip Flare Jean",price:85.99,
            description:"Zip-detail flare denim for the late-night crowd. Wear it when the night calls for something more.",
            imageUrl:CDN+"rn-image_picker_lib_temp_1a0b9127-132e-4722-a6ee-fbe2a349d6c4.png",category:"denim",
            sizes:["28","30","32","34","38"],colors:["Nuit Blanche"]),
        Product(id:"off-white-lie",handle:"off-white-lie-flare-jean",title:"Off-White Lie Flare Jean",price:89.99,
            description:"A pale, off-white flare denim that reads clean and deliberate. Effortless dressed up or down.",
            imageUrl:CDN+"rn-image_picker_lib_temp_7aba15e3-b953-40b3-ba8d-73a7a596e973.jpg",category:"denim",
            sizes:["24","26","28","30","32"],colors:["Off-White"]),
        Product(id:"rosetta-jean",handle:"rosetta-distressed-flare-jean",title:"Rosetta Distressed Flare Jean",price:79.99,
            description:"A feminine-leaning distressed flare with warm undertones. Pairs easily across the collection.",
            imageUrl:CDN+"rn-image_picker_lib_temp_e074f113-082a-4e38-afa3-e1c5cfc3c7d8.png",category:"denim",
            sizes:["28","30","32","34","36"],colors:["Rosetta"]),
        Product(id:"noir-traffic",handle:"noir-traffic-wide-jean",title:"Noir Traffic Wide Jean",price:79.99,
            description:"A wide-leg silhouette in noir with graphic detail. Relaxed fit, unisex sizing.",
            imageUrl:CDN+"rn-image_picker_lib_temp_9e74971b-f52b-440a-adc9-c1e8301fba21.png",category:"denim",
            sizes:["S","M","L","XL","2XL"],colors:["Black"],isNew:true,tags:["New"]),
        Product(id:"casanegra",handle:"casanegra-leather-flare-zip-pants",title:"CasaNegra Leather Flare Zip Pants",price:159.99,
            description:"Premium leather-look flare zip pants in deep black. Structured silhouette, bold finish, built to own a room.",
            imageUrl:CDN+"rn-image_picker_lib_temp_9db4135b-f026-4caa-a943-a03e7836d978.png",category:"denim",
            sizes:["28","29","30","32","34"],colors:["Nero"],isFeatured:true,tags:["Premium"]),
        Product(id:"kech",handle:"kech-leather-flare-zip-pants",title:"Kech Leather Flare Zip Pants",price:159.99,
            description:"Leather-look flare zip pants in a warmer tonal palette — Casablanca colorway.",
            imageUrl:CDN+"rn-image_picker_lib_temp_b005d4b3-c76c-4979-b81c-6dfd0bfddaec.png",category:"denim",
            sizes:["28","29","30","32","34"],colors:["Casablanca"]),

        // TOPS
        Product(id:"barolo",handle:"barolo-tweed-zip-overshirt",title:"Barolo Tweed Zip Overshirt",price:149.99,
            description:"A rich tweed zip overshirt in deep burgundy tones. Designed to layer, to lead, and to last.",
            imageUrl:CDN+"rn-image_picker_lib_temp_c959cd8c-ff24-4b2b-a1fa-7b5ae868ac39.png",category:"tops",
            sizes:["XS","S","M","L","XL"],colors:["Barolo"],isFeatured:true),
        Product(id:"bluefin",handle:"the-bluefin-relaxed-shirt",title:"Bluefin Relaxed Shirt",price:45.99,
            description:"A clean, relaxed button-up in a quiet palette. The everyday reach — effortless and considered.",
            imageUrl:CDN+"rn-image_picker_lib_temp_598395a9-163e-4f2d-b31d-e5ed6ad33f23.png",category:"tops",
            sizes:["XS","S","M","L","XL"],colors:["Bluefin Stripe"]),
        Product(id:"moula",handle:"moula-caramel-cable-knit-polo",title:"Moula Caramel Cable Knit Polo",price:129.99,
            description:"A cable knit polo in warm caramel tones. Luxury dressed casually — premium tactile construction, refined silhouette.",
            imageUrl:CDN+"rn-image_picker_lib_temp_5c622955-3d2e-47b6-9d63-cd0c09c8b715.jpg",category:"tops",
            sizes:["XS","S","M","L","XL"],colors:["Caramel"],isFeatured:true,isNew:true,tags:["New"]),
        Product(id:"olive-affair",handle:"olive-affair-retro-panel-jacket",title:"Olive Affair Retro Panel Jacket",price:84.99,
            description:"A retro-paneled jacket in olive tones with a structured athletic cut. A utility piece built for daily movement.",
            imageUrl:CDN+"rn-image_picker_lib_temp_8efde421-c08e-4c27-840e-dc3073369bd9.png",category:"tops",
            sizes:["S","M","L"],colors:["Olive"]),
        Product(id:"taupe-secret",handle:"taupe-secret-retro-panel-jacket",title:"Taupe Secret Retro Panel Jacket",price:84.99,
            description:"Retro panel jacket in taupe — a quieter take on the same athletic silhouette as the Olive Affair.",
            imageUrl:CDN+"rn-image_picker_lib_temp_712817b7-81a9-4dfe-9b9c-7623e4914fad.jpg",category:"tops",
            sizes:["S","M","L"],colors:["Taupe"]),
        Product(id:"smoke-signal",handle:"smoke-signal-spray-tee",title:"Smoke Signal Spray Tee",price:74.99,
            description:"A spray-effect graphic tee with a considered fade. The foundational layer — wear it under a jacket, over a bodysuit, or on its own.",
            imageUrl:CDN+"rn-image_picker_lib_temp_5a630211-5cae-4784-8d29-e11b5e492bb8.png",category:"tops",
            sizes:["XS","S","M","L","XL"],colors:["Smoke"]),
        Product(id:"taqburni",handle:"taqburni-velour-polo-shirt",title:"Taqburni Velour Polo Shirt",price:99.99,
            description:"A velour polo shirt that bridges the gap between the tracksuit line and tailored tops. Textured, intentional, limited.",
            imageUrl:CDN+"rn-image_picker_lib_temp_91a9cfbb-ceb9-4542-a08c-9ad837649642.jpg",category:"tops",
            sizes:["XS","S","M","L","XL"],colors:["Taqburni"],isNew:true,tags:["New"]),
        Product(id:"mint-tee",handle:"mint-condition-panel-tee",title:"Mint Condition Panel Tee",price:35.99,
            description:"An oversized panel tee in mint green and white snow colorways. Relaxed unisex fit from Melato Studios.",
            imageUrl:CDN+"rn-image_picker_lib_temp_8ea818d0-fc15-4f00-9b8d-5eaad4901bd8.png",category:"tops",
            sizes:["M","L","XL"],colors:["Mint Green","White Snow"],isNew:true,tags:["New"]),

        // ACCESSORIES
        Product(id:"atlas-dopp",handle:"atlas-dopp-kit",title:"Atlas Dopp Kit",price:69.99,
            description:"A compact, structured travel kit in premium coated canvas with monogram detail. Carry it with intent.",
            imageUrl:CDN+"rn-image_picker_lib_temp_b396a57a-a5d3-43b6-be1b-293f78d9d4d3.png",category:"accessories",
            sizes:["One Size"],colors:["Atlas"]),
        Product(id:"atlas-duffle",handle:"atlas-woven-duffle",title:"Atlas Woven Duffle",price:189.99,
            description:"A woven duffle bag with premium hardware and structured construction. For the traveler who doesn't compromise.",
            imageUrl:CDN+"rn-image_picker_lib_temp_f65ed62e-dada-4c49-9b8b-223c9fee8064.png",category:"accessories",
            sizes:["One Size"],colors:["Atlas"],isFeatured:true),
        Product(id:"emerald-tie",handle:"emerald-solstice-tile-geometric-tie",title:"Emerald Solstice Tile Geometric Tie",price:79.99,
            description:"A geometric tile pattern tie in emerald tones. Part of the Zellige capsule.",
            imageUrl:CDN+"rn-image_picker_lib_temp_573e449e-fd4b-4299-b40b-927b8d05542f.jpg",category:"accessories",
            sizes:["One Size"],colors:["Emerald"]),
        Product(id:"knotorious",handle:"knotorious-monogram-tie",title:"Knotorious Monogram Tie",price:89.99,
            description:"A monogram tie with an all-over Melato pattern. Wearable brand identity at its most deliberate.",
            imageUrl:CDN+"rn-image_picker_lib_temp_5ef14989-eb7d-4cad-ae28-7f3160333e5b.jpg",category:"accessories",
            sizes:["One Size"],colors:["Knotorious"]),
        Product(id:"rosewood-tie",handle:"rosewood-checkerboard-tie",title:"Rosewood Checkerboard Tie",price:79.99,
            description:"Checkerboard pattern tie in rosewood tones. Clean geometry, warm colour.",
            imageUrl:CDN+"rn-image_picker_lib_temp_26388381-558a-46d5-a184-8d9d6f37b66a.jpg",category:"accessories",
            sizes:["One Size"],colors:["Rosewood"]),
        Product(id:"ruby-tie",handle:"ruby-labyrinth-geometric-tie",title:"Ruby Labyrinth Geometric Tie",price:79.99,
            description:"A deep ruby geometric labyrinth tie. Bold pattern, refined execution.",
            imageUrl:CDN+"rn-image_picker_lib_temp_092c6019-0ff4-46fe-b879-45da3a4a6612.jpg",category:"accessories",
            sizes:["One Size"],colors:["Ruby"]),
        Product(id:"sunlit-tie",handle:"sunlit-atrium-geometric-tie",title:"Sunlit Atrium Geometric Tie",price:79.99,
            description:"A warm, golden-hour geometric tie in sunlit tones. A versatile accent that works across the collection.",
            imageUrl:CDN+"rn-image_picker_lib_temp_86a1b481-6dcc-4547-abf8-46c00ec6e660.png",category:"accessories",
            sizes:["One Size"],colors:["Sunlit"]),
        Product(id:"ivy-harness",handle:"ivy-trellis-harness-suspenders",title:"Ivy Trellis Harness Suspenders",price:79.99,
            description:"Structured harness suspenders in an ivy trellis pattern. A collector's item.",
            imageUrl:CDN+"rn-image_picker_lib_temp_d7b1a9ee-f657-40d0-ae74-8c04f65d1005.jpg",category:"accessories",
            sizes:["One Size"],colors:["Ivy"]),
        Product(id:"salopette",handle:"salopette-de-salo-harness-suspenders",title:"Salopette de Salo Harness Suspenders",price:79.99,
            description:"A fashion-forward harness suspender set with architectural construction. Worn as a centrepiece or layering accent.",
            imageUrl:CDN+"rn-image_picker_lib_temp_734dacab-a721-43d9-af41-79ace1525cba.jpg",category:"accessories",
            sizes:["One Size"],colors:["Salo"]),

        // EVE'S WARDROBE
        Product(id:"blue-hour",handle:"blue-hour-alibi-mesh-bodysuit",title:"Blue Hour Alibi Mesh Bodysuit",price:199.99,
            description:"A sheer mesh bodysuit designed for the blue hour — the quiet drama between day and night.",
            imageUrl:CDN+"rn-image_picker_lib_temp_de1c346b-e085-4fe2-8789-239027b20b34.jpg",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Blue Hour"],isFeatured:true,isNew:true,tags:["Eve's Wardrobe"]),
        Product(id:"body-language",handle:"body-language-mesh-bodysuit",title:"Body Language Mesh Bodysuit",price:199.99,
            description:"Mesh bodysuit with deliberate cut and controlled exposure. Wear it loud or quiet, but wear it on purpose.",
            imageUrl:CDN+"melato-body-language-cocoa-mesh-bodysuit-front.jpg",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Cocoa"],tags:["Eve's Wardrobe"]),
        Product(id:"cognac-skirt",handle:"cognac-confession-leather-pencil-skirt",title:"Cognac Confession Leather Pencil Skirt",price:130.00,
            description:"A leather pencil skirt in cognac — precise, bold, and entirely deliberate.",
            imageUrl:CDN+"rn-image_picker_lib_temp_678fde1f-5e9c-4882-998c-022bfe155574.jpg",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Cognac"]),
        Product(id:"noir-alibi",handle:"noir-alibi-lace-corset-dress",title:"Noir Alibi Lace Corset Dress",price:319.99,
            description:"The statement piece of Eve's Wardrobe. A lace corset dress in noir with structured boning and deliberate silhouette. Limited production.",
            imageUrl:CDN+"rn-image_picker_lib_temp_90c7e6e3-5499-40e6-8f1f-4ec547f31dd4.jpg",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Noir"],isFeatured:true,isNew:true,tags:["Eve's Wardrobe","Statement"]),
        Product(id:"noir-memoir",handle:"noir-memoir-wrap-pencil-skirt",title:"Noir Memoir Wrap Pencil Skirt",price:110.00,
            description:"A wrap pencil skirt in noir with a clean, tailored finish. Understated — every bit as intentional.",
            imageUrl:CDN+"rn-image_picker_lib_temp_b1e85891-55d0-49bf-9656-13ccb456b4b4.jpg",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Noir"]),
        Product(id:"dawn-to-dusk",handle:"dawn-to-dusk-three-piece-undergarment-set",title:"Dawn-to-Dusk Three Piece Undergarment Set",price:119.99,
            description:"A three-piece undergarment set designed for all-day comfort and intentional styling.",
            imageUrl:CDN+"rn-image_picker_lib_temp_93d6752e-fc15-4803-af49-22d5a50e92a4.png",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Ivory","Noir"]),
        Product(id:"side-note",handle:"side-note-lace-rib-top",title:"Side Note Lace Rib Top",price:59.99,
            description:"A lace rib top that layers under everything or stands alone. The entry point to Eve's Wardrobe.",
            imageUrl:CDN+"rn-image_picker_lib_temp_3899bbd8-e29d-483f-b836-bda0c1a3b8d8.jpg",category:"eves-wardrobe",
            sizes:["S","M","L"],colors:["Ivory","Noir"]),
    ]

    static let faq: [FaqItem] = [
        FaqItem(question:"How long does order processing take?",answer:"Orders are usually prepared within 1 to 3 business days. During limited drops, holidays, or high-volume periods, processing may take slightly longer."),
        FaqItem(question:"How long does shipping take?",answer:"Delivery times depend on destination and selected shipping method. Final shipping options and estimated delivery windows appear at checkout."),
        FaqItem(question:"Do you offer complimentary shipping?",answer:"Yes — complimentary shipping on all orders, no minimum required."),
        FaqItem(question:"Do you ship internationally?",answer:"Yes — we ship worldwide with complimentary standard shipping. Any duties or import taxes are calculated at checkout or collected by the carrier."),
        FaqItem(question:"Will I receive tracking?",answer:"Yes. Once your order ships, tracking details are sent to the email or phone number used at checkout. Tracking may take up to 24 hours to update."),
        FaqItem(question:"Can I change or cancel my order?",answer:"Contact support@melato.ca immediately. Once an order has been processed or shipped, changes may no longer be possible."),
        FaqItem(question:"How does Melato fit?",answer:"Melato pieces are designed with a relaxed athletic fit. Choose your usual size for a clean silhouette, or size up if you prefer a looser look."),
        FaqItem(question:"What materials are used?",answer:"Materials vary by product and collection. Each product page includes its own fabric composition and care notes where available."),
        FaqItem(question:"How do I care for my Melato pieces?",answer:"Wash cold on a gentle cycle, wash inside out, avoid bleach, and hang dry when possible. Do not iron over embroidery, prints, or branded details."),
        FaqItem(question:"Will sold-out colorways restock?",answer:"Melato drops are limited. Some pieces may restock, but many colorways are released in small quantities and may not return once sold out."),
        FaqItem(question:"What is your return window?",answer:"Eligible items may be returned within 30 days of delivery. Items must be unworn, unwashed, with original tags attached and in original packaging."),
        FaqItem(question:"How do I start a return?",answer:"Email support@melato.ca with your order number, item details, and return reason. Our team will review and provide next steps."),
        FaqItem(question:"Do you offer exchanges?",answer:"Exchanges depend on availability. The fastest option is usually to place a new order and return the original eligible item."),
        FaqItem(question:"What if my item arrives damaged or incorrect?",answer:"Contact support@melato.ca immediately with your order number and photos. We'll assess and resolve quickly."),
    ]

    static func featured() -> [Product] { products.filter(\.isFeatured) }
    static func newArrivals() -> [Product] { products.filter(\.isNew) }
    static func byCategory(_ id: String) -> [Product] {
        id == "all" ? products : products.filter { $0.category == id }
    }
    static func search(_ query: String) -> [Product] {
        let q = query.lowercased()
        return products.filter {
            $0.title.lowercased().contains(q) ||
            $0.category.lowercased().contains(q) ||
            $0.description.lowercased().contains(q)
        }
    }
}
